In [2]:
#python is high level language
print("hello meena")


hello meena


In [3]:
print("A","B",sep="*")

A*B


In [8]:
print("hello meena",sep="_",end=" thank you ")
print("hi")

hello meena thank you hi


In [11]:
name="meena"
age=20
type(name)


str

In [12]:
type(age)

int

In [13]:
print(f"my name is {name}")

my name is meena


In [35]:
choice=int(input("enter the your choice"))
deposit=int(input("enter the deposit"))
withdraw=int(input("enter the withdraw amt"))

if(choice==1):
    if(deposit>withdraw):
       print("withdraw can be done")
    else:
        print("cant be withdrawn")
elif(choice==2):
    print(f"Enter the deposit amt{deposit}")
    if(deposit>withdraw):
        print("withdrawn")
    else:
        print("cant withdraw")
elif(choice==3):
    print(f"display balance{deposit-withdraw}")
else:
    print("Invalid choice")

enter the your choice 3
enter the deposit 3000
enter the withdraw amt 2000


display balance1000


In [56]:
for i in range(3):
    for j in range(i+1):
        print("*",end=" ")
    print()
        

* 
* * 
* * * 


In [74]:
for i in range(0,3):
    for j in range(i+1):
        print(j+1,end="")
    print()

1
12
123


In [107]:
for i in range(7):
    for j in range(0,7,1):
        if i==0 or i==6 or j==0 or j==6:
           print("*",end=" ")
        else:
            print(" ",end=" ")
    print(" ")

      

* * * * * * *  
*           *  
*           *  
*           *  
*           *  
*           *  
* * * * * * *  


In [138]:
for i in range(3):
    for j in range(0,3,1):
        if i==j :
           print("*",end=" ")
        elif i==2 and j==0 or i==0 and j==2 :
            print("*", end=" ")
        else:
            print(" ",end=" ")
    print(" ")


*   *  
  *    
*   *  


In [181]:
for i in range(3):
    num = 65
    for j in range(i+1):
        print(chr(num), end=" ")
        num+=1
    print()

A 
A B 
A B C 


In [9]:
for i in range(5):
    for j in range(7):
        if (i==1)or(i==0 and j%3!=0)or (i==2 and( j!=6 and j!=0)) or (i==3 and (j==2 or j==3 or j==4)) or (i==4 and j==3):
           print("*",end=" ")
        else:
            print(" ",end=" ")
    print()


  * *   * *   
* * * * * * * 
  * * * * *   
    * * *     
      *       


In [13]:
user="meena"
user[0:1]


'm'

In [20]:
user=input("enter a string")
user1=user[::-1]
if user==user1:
    print("yes")
else:
    print("no")

enter a string 343


yes


In [22]:
user="india is a country "
user.title()

'India Is A Country '

In [24]:
user1="india"
user1.count("i")

2

In [35]:
a="malayalam"
for i in a:
    for j in a:
        st = ""
        st += j
        if i==j:
          continue
print(st)

m


In [37]:
user="india"
user[::-1]

'aidni'

In [63]:
list1 = ["a","e","i","o","u"]
n = input("Enter a strng:").lower()
count = 0 
for x in n:
    if x in list1:
        count+=1
    print(x)
print("count:",count, end=" ")


Enter a strng: MEE


m
e
e
count: 2 

In [83]:
def count(string):
    return{x:string.count(x) for x in string}
count("meena")

    

{'m': 1, 'e': 2, 'n': 1, 'a': 1}

In [99]:
n=input("enter a password")
fif = n[4]
if len(n)<6:
    print("Invalid")
if (fif.isdigit() and 1<=int(fif)<=5):
    print("valid")
else:
    print("invalid")
    

enter a password sfsh437


valid


In [118]:
for i in range(7):
    for j in range(7):   
        if (i==3)or(j==3)or (i==j) or (i+j==6):
           print("*",end=" ")
        else:
            print(" ",end=" ")
    print()


*     *     * 
  *   *   *   
    * * *     
* * * * * * * 
    * * *     
  *   *   *   
*     *     * 


In [136]:
for i in range(5):
    for j in range(5):   
        if (j==2 and i==0)  or (i==2 and j==2 ) or (i==4 and j==2) or (i==1 and j==1) or (i==3 and j==3) or (i==1 and j==3) or (i==3 and j==1) :
           print("-",end=" ")
        elif(i==1 and (j==0 or j==4)) or (i==3 and (j==0 or j==4)):
            print(" ",end=" ")
        else:
            print("*",end=" ")
    print()

* * - * * 
  - * -   
* * - * * 
  - * -   
* * - * * 


In [9]:
bag1=['apple','mango','water','sweet']
bag2=['water','apple','chips','mango']
bag3=bag1+bag2

In [12]:
set(bag3)

{'apple', 'chips', 'mango', 'sweet', 'water'}

In [13]:
bag3.sort()

In [14]:
bag3

['apple', 'apple', 'chips', 'mango', 'mango', 'sweet', 'water', 'water']

In [16]:
set(bag3)

{'apple', 'chips', 'mango', 'sweet', 'water'}

a= int(input("enter the number"))


In [18]:
b=float(input("enter the number"))

enter the number 12.2


In [17]:
a,b=map (int,input("enter a number").split())
print(a+b)

enter a number 12 13


25


In [19]:
a,b=map(float,input("enter a number").split())
print(a+b)

enter a number 12.3 12.3


24.6


In [20]:
import random
nums=random.randint(1,10)
guess=None
while(nums!=guess):
    guess=int(input("enter a number"))
    if(guess>nums):
        print("the number is greater, reduce the number")
    elif(guess<nums):
        print("the number is lesser, increase the number")
    else:
        print("yes u guess it right")              
print()    

enter a number 3


the number is lesser, increase the number


enter a number 2


the number is lesser, increase the number


enter a number 4


yes u guess it right



In [21]:
nums=list(map(int,input("enter a numbers").split()))
nums


enter a numbers 12 13 14


[12, 13, 14]

In [29]:
nums=input("enter the number").split(',')

enter the number a f g


In [22]:
['a', 'f', 'g']
x=eval('10+20')
x

30

In [23]:
name=input("enter a word")
if(name=='admin'):
    print("yes")
else:
    print("not true")

enter a word mee


not true


In [24]:
a="      hello"
a.lstrip()

'hello'

In [25]:
s=input("enter the number").lower()
print(s)

enter the number 12


12


In [26]:

s=input('enter a string')
s.isalpha()
s.isnumeric()
s.isalnum()

enter a string djs3


True

In [30]:
a=hash("hello")

In [31]:
a

-3045618069611578120

In [39]:
a1={1:"meena",2:"mithu","age":23}
a1

{1: 'meena', 2: 'mithu', 'age': 23}

In [40]:
a1[2]

'mithu'

In [43]:
a1["age"]=40
a1

{1: 'meena', 2: 'mithu', 'age': 40}

In [44]:
del a1[1]

a1

In [45]:
print(a1)

{2: 'mithu', 'age': 40}


In [47]:
for keys,values in a1.items():
    print(keys,values)

2 mithu
age 40


In [82]:
a3=merge_dict=a1| a2

In [83]:
a3

{2: 'mithu', 'age': 40, 3: 'meena', 4: 'mit'}

In [91]:
def find_lar(nums):
    max_val=nums[0]
    for num in nums:
        if(max_val>num):
           num=max_val
    return num;
find_lar([1,2,3,2,1,4,5])

5

In [94]:
from scipy import stats
dat1=[1,2,45,2,213,2,1,23,2]
result=stats.mode(dat1)

In [95]:
result

ModeResult(mode=np.int64(2), count=np.int64(4))

In [107]:
for i in range(9):
    for j in range(3):
        if(i==1):
            print("A", end=" ")
        elif(i==4):
            print("B", end=" ")
        elif(i==7):
            print("C", end=" ")
        elif((i==0 or i==2) and j==1):
            print("1", end=" ")
        elif((i==3 or i==5) and j==1):
            print("2", end=" ")
        elif((i==6 or i==8) and j==1):
            print("3", end=" ")
        else:
            print("*", end=" ")
            
    print()

* 1 * 
A A A 
* 1 * 
* 2 * 
B B B 
* 2 * 
* 3 * 
C C C 
* 3 * 


In [111]:
tup2=((1,2,3),(4,5,6),(7,8,9))
           
tup3=tup2[0][1]*tup2[1][1]*tup2[2][1]


In [112]:
tup3

80

In [45]:
for i in range(7):
    for j in range(7):
        if(i==3 or j==3) or ((i==1 or i==5) and (j==2 or j==4)) or((i==2 or i==4) and (j==1 or j==2 or j==4 or j==5)) :
            print("*", end=" ")
        else:
            print(" ", end=" ")
            
    print()

      *       
    * * *     
  * * * * *   
* * * * * * * 
  * * * * *   
    * * *     
      *       


In [1]:
try:
    print(3/0)
except Exception:
    print("error")

error


In [7]:
numbers=[1,2,0]
for num in numbers:
    try:
      res=10/num
      print(res)
    except Exception as e:
      print("error")
    finally:
      print("thank you")

10.0
thank you
5.0
thank you
error
thank you


In [11]:
def val_age(age):
    if(age>18):
        raise Exception("Invalid age")
    else:
        print("not eligible")
try:
    val_age(20)
except Exception as e:
    print("error")

error


In [16]:
def val_age(age):
    if(age>18):
        raise lessageException(" age")
    elif(age<40):
        raise moreageException("not eligible")
    else:
        print("good")
class lessageException(Exception):
    pass
class moreageException(Exception):
    pass


In [42]:
def name(firstname,lastname):
    if(len(firstname)<3):
        raise nameException("Error")
    elif(len(lastname)<3):
        raise lastnameException("error")
    elif(firstname and lastname).isalpha()==False:
        raise invalidException("it should be only char")
    else:
        print(f"name is good{firstname}{lastname}")
class nameException(Exception):
    pass
class lastnameException(Exception):
    pass
class invalidException(Exception):
    pass
try:
    firstname=input("enter your name")
    lastname=input("enter your name")
    name(firstname,lastname)
except nameException as e:
    print(e)
except lastnameException as en:
    print(en)
except invalidException as ene:
    print(ene)
    



enter your name sh21
enter your name s21


it should be only char


In [55]:
for i in range(5):
    for j in range(5):
        if(i==1 and j==2) or (i==2 and j==1) or (i==2 and j==3) or (i==3 and j==2):
            print("1", end=" ")
        elif(i==2 and j==2):
            print("2",end=" ")
        elif(i==0 and (j==1 or j==3)) or (i==2 and (j==0 or j==4)) or (i==4 and(j==1 or j==3)):
            print("*",end=" ")
        else:
            print(" ", end=" ")
            
    print()

  *   *   
    1     
* 1 2 1 * 
    1     
  *   *   


In [65]:
import numpy as np
a=np.array([1,2,3][1,2,3])
print(a)

[1 2 3]


In [66]:
type(a)

numpy.ndarray

In [68]:
print(a.shape)

(3,)


In [67]:
print(np.median(a))

2.0


In [62]:
print(np.mean(a))

2.7777777777777777


In [89]:
for i in range(7):
    for j in range(7):
        if(i==5 and j==0) or (i==1 and j==6):
            print("4", end=" ")
        elif(i==1 and j==0) or (i==5 and j==6):
            print("2", end=" ")
        elif(i==3 and j==1) or (i==3 and j==5):
            print("1",end=" ")
        elif(i==3 and j==3):
            print("0",end=" ")
        elif(i==j or i+j==6) or ((i==2 or i==3 or i==4) and j==0 or j==6):
            print("*",end=" ")
        else:
            print(" ", end=" ")
            
    print()

*           * 
2 *       * 4 
*   *   *   * 
* 1   0   1 * 
*   *   *   * 
4 *       * 2 
*           * 


In [155]:
for i in range(13):
    for j in range(9):
        if(i==0 and (j==1 or j==2 or j==4 or j==6 or j==7)) or (i==1 and (j==2 or j==3 or j==5 or j==6)) or (i==2 and (j==3 or j==5)) :
            print(" ",end=" ")
        elif(i==5 and (j==2 or j==6)) or (i==6 and(j==1  or j==7)) or (i==7 and (j==0 or j==8)) or (i==10 and (j==3 or j==5)):
            print(" ",end=" ")
        elif(i==12 and(j==1 or j==2 or j==3 or j==4 or j==5 or j==6 or j==7)) or (i==11 and (j==2 or j==3 or j==5 or j==6)):
            print(" ",end=" ")
        else:
            print("*", end=" ")
            
    print()

*     *   *     * 
* *     *     * * 
* * *   *   * * * 
* * * * * * * * * 
* * * * * * * * * 
* *   * * *   * * 
*   * * * * *   * 
  * * * * * * *   
* * * * * * * * * 
* * * * * * * * * 
* * *   *   * * * 
* *     *     * * 
*               * 


In [99]:
a=np.zeros((2,2))

In [100]:
a

array([[0., 0.],
       [0., 0.]])

In [106]:
a1=np.array([[1,2,3,4],[5,6,7,8]])


In [107]:
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
a1[1][1]

np.int64(6)

In [109]:
a1[0]

array([1, 2, 3, 4])

In [111]:
a1[1][3]=25

In [112]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 25]])

In [123]:
sub_array=a1[0:1,1:2]

In [125]:
sub_array

array([[2]])

In [130]:
a3=np.zeros((10,10))

In [131]:
a3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [139]:
a3[1][3]=1

In [142]:
a3[8][3]=1

In [143]:
a3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [147]:
np.count_nonzero(a3)

np.int64(2)

In [169]:
import pandas as pd

In [172]:
df=pd.read_csv("placements.csv")

In [173]:
df

Name  Marks
0   meena     50
1   nisha     80
2  suhana     60

In [181]:
print(df['Name'].min())

meena


In [180]:
print(df['Name'].max())

suhana


In [182]:
a=df['Marks']>70
print(a)

0    False
1     True
2    False
Name: Marks, dtype: bool


In [156]:
# ANSI color codes
RED = "\033[91m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
GREEN = "\033[92m"
RESET = "\033[0m"

for i in range(13):
    for j in range(9):
        if (i==0 and (j==1 or j==2 or j==4 or j==6 or j==7)) or \
           (i==1 and (j==2 or j==3 or j==5 or j==6)) or \
           (i==2 and (j==3 or j==5)):
            print(" ", end=" ")

        elif (i==5 and (j==2 or j==6)) or \
             (i==6 and (j==1 or j==7)) or \
             (i==7 and (j==0 or j==8)) or \
             (i==10 and (j==3 or j==5)):
            print(" ", end=" ")

        elif (i==12 and (j in [1,2,3,4,5,6,7])) or \
             (i==11 and (j==2 or j==3 or j==5 or j==6)):
            print(" ", end=" ")

        else:
            # Color logic for butterfly parts
            if i < 4:
                print(RED + "*" + RESET, end=" ")
            elif 4 <= i <= 8:
                print(BLUE + "*" + RESET, end=" ")
            else:
                print(YELLOW + "*" + RESET, end=" ")

    print()

*     *   *     * 
* *     *     * * 
* * *   *   * * * 
* * * * * * * * * 
* * * * * * * * * 
* *   * * *   * * 
*   * * * * *   * 
  * * * * * * *   
* * * * * * * * * 
* * * * * * * * * 
* * *   *   * * * 
* *     *     * * 
*               * 


In [157]:
RED = "\033[91m"
RESET = "\033[0m"

for i in range(5):
    for j in range(7):
        if (i==1) or (i==0 and j%3!=0) or (i==2 and (j!=6 and j!=0)) \
           or (i==3 and (j==2 or j==3 or j==4)) or (i==4 and j==3):
            print(RED + "*" + RESET, end=" ")
        else:
            print(" ", end=" ")
    print()

  * *   * *   
* * * * * * * 
  * * * * *   
    * * *     
      *       


In [159]:
PURPLE = "\033[95m"
RESET = "\033[0m"

for i in range(13):
    for j in range(9):
        if(i==0 and (j==1 or j==2 or j==4 or j==6 or j==7)) or \
          (i==1 and (j==2 or j==3 or j==5 or j==6)) or \
          (i==2 and (j==3 or j==5)):
            print(" ", end=" ")

        elif(i==5 and (j==2 or j==6)) or \
            (i==6 and (j==1 or j==7)) or \
            (i==7 and (j==0 or j==8)) or \
            (i==10 and (j==3 or j==5)):
            print(" ", end=" ")

        elif(i==12 and (j in [1,2,3,4,5,6,7])) or \
            (i==11 and (j==2 or j==3 or j==5 or j==6)):
            print(" ", end=" ")

        else:
            print(PURPLE + "*" + RESET, end=" ")

    print()

*     *   *     * 
* *     *     * * 
* * *   *   * * * 
* * * * * * * * * 
* * * * * * * * * 
* *   * * *   * * 
*   * * * * *   * 
  * * * * * * *   
* * * * * * * * * 
* * * * * * * * * 
* * *   *   * * * 
* *     *     * * 
*               * 
